import { IGenre, providerFilter } from '../SearchQueryTypes';

export const INIT_SORT_ORDER = 'popularity.desc';
export const INIT_YEARS_STATE = [1900, 2022];
export const INIT_RATING_STATE = [0, 10];
export const INIT_REGION = 'RU';
export const INIT_GENRES_STATE: IGenre[] = [
  { id: 28, name: 'Action', isApplied: false },
  { id: 12, name: 'Adventure', isApplied: false },
  { id: 16, name: 'Animation', isApplied: false },
  { id: 35, name: 'Comedy', isApplied: false },
  { id: 80, name: 'Crime', isApplied: false },
  { id: 99, name: 'Documentary', isApplied: false },
  { id: 18, name: 'Drama', isApplied: false },
  { id: 10751, name: 'Family', isApplied: false },
  { id: 14, name: 'Fantasy', isApplied: false },
  { id: 36, name: 'History', isApplied: false },
  { id: 27, name: 'Horror', isApplied: false },
  { id: 10402, name: 'Music', isApplied: false },
  { id: 9648, name: 'Mystery', isApplied: false },
  { id: 10749, name: 'Romance', isApplied: false },
  { id: 878, name: 'Science Fiction', isApplied: false },
  { id: 10770, name: 'TV Movie', isApplied: false },
  { id: 53, name: 'Thriller', isApplied: false },
  { id: 10752, name: 'War', isApplied: false },
  { id: 37, name: 'Western', isApplied: false },
];
export const INIT_PROVIDERS_STATE: providerFilter[] = [
  { id: 8, isApplied: false },
  { id: 119, isApplied: false },
  { id: 2, isApplied: false },
  { id: 3, isApplied: false },
  { id: 115, isApplied: false },
  { id: 116, isApplied: false },
  { id: 113, isApplied: false },
  { id: 11, isApplied: false },
  { id: 100, isApplied: false },
  { id: 534, isApplied: false },
  { id: 350, isApplied: false },
  { id: 190, isApplied: false },
  { id: 521, isApplied: false },
  { id: 501, isApplied: false },
  { id: 475, isApplied: false },
  { id: 546, isApplied: false },
  { id: 551, isApplied: false },
  { id: 554, isApplied: false },
  { id: 559, isApplied: false },
  { id: 444, isApplied: false },
  { id: 556, isApplied: false },
  { id: 557, isApplied: false },
  { id: 567, isApplied: false },
  { id: 445, isApplied: false },
  { id: 569, isApplied: false },
  { id: 315, isApplied: false },
  { id: 677, isApplied: false },
  { id: 570, isApplied: false },
  { id: 577, isApplied: false },
  { id: 117, isApplied: false },
  { id: 188, isApplied: false },
];
